##Shipping service is responsible for finding the distance of the package to be shipped and calculate the price based on that.
##
##Shipping service is written in Java, Hence we need to install Java.
##
##1. Install Maven, This will install Java too
##
##```sql
##  # yum install maven -y
##```
##
##1. As per the standard process, we always run the applications as a normal user.
##
##Create a user
##
##```sql
##  # useradd roboshop
##```
##
##1. Download the repo
##
##```bash
##$ cd /home/roboshop
##$ curl -s -L -o /tmp/shipping.zip "https://github.com/roboshop-devops-project/shipping/archive/main.zip"
##$ unzip /tmp/shipping.zip
##$ mv shipping-main shipping
##$ cd shipping
##$ mvn clean package
##$ mv target/shipping-1.0.jar shipping.jar
##```
##
##1. Update SystemD Service file
##
##Update `CARTENDPOINT` with Cart Server IP.
##
##Update `DBHOST` with MySQL Server IP
##
##2. Copy the service file and start the service.
##
##```sql
##  # mv /home/roboshop/shipping/systemd.service /etc/systemd/system/shipping.service
##  # systemctl daemon-reload
##  # systemctl start shipping
##  # systemctl enable shipping
###```
#
#- name: Installing Maven
#  ansible.builtin.package:
#    name: maven
#    state: present
#
#- name: Download and extract {{COMPONENT} and create App User
#  include_role:
#     name: common
#     tasks_from: download
#
#- name: Make maven package
#  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
#  args:
#    chdir: /home/roboshop/{{COMPONENT}}
#  become_user: roboshop
#
#- name: Copy SystemD and Start Service
#  include_role:
#    name: common
#    tasks_from: systemd

- name: Configuring {{COMPONENT}} maven
  include_role:
    name: common
    tasks_from: maven
