# Launch instances, runs some tasks
# and then terminate them

- name: Playbook to create the ec2, do a run run and then self-destroy
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    security_group_id: "sg-01707a1347b204f43"
    image: "ami-0bb6af715826253bf"
    region: "us-east-1"
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: ansible-dryrun-check
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 40
        timeout: 90
      loop: "{{ ec2.instances }}"

    - name: Test Msg
      debug:
        msg: "Test Run"

    - name: Import the role
      import_role:
         name: "{{role_name }}"
      ignore_errors: yes
      become: yes

    - name: Terminate Instance
      amazon.aws.ec2:
        region: "{{ region }}"
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'


