- name: Install Python3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Search & Replace UID in the payment.ini
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/payment.ini
    regexp: '^uid'
    line:  uid = APPUSER.uid

- name: Search & Replace GID in the payment.ini
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/payment.ini
    regexp: '^gid'
    line:  gid = APPUSER.gid
