- name: Install Python3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed
- name: Download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Installing python dependencies as per requirements file
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Search & Replace UID in the payment.ini
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line:  uid = "{{ APPUSER.uid }}"

- name: Search & Replace GID in the payment.ini
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line:  gid = "{{ APPUSER.group }}"

- name: Copy SystemD and Start Service
  include_role:
    name: common
    tasks_from: systemd

