- name: Install Python3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Registering the UID
  ansible.builtin.shell: id -u roboshop
  register: USER

- name: Registering the UGD
  ansible.builtin.shell: id -g roboshop
  register: GROUP

- name: Pritning Output
  debug:
      msg: "{{OUT}} and {{GROUP}}"
