- name: Install Python3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Registering the output
  ansible.builtin.shell: id roboshop
  register: OUT

- name: Pritning Output
  debug:
      msg: "{{OUT}}"
