- name: Install Python3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Search & Replace UID in the payment.ini
  ansible.builtin.replace:
    path: /home/roboshop/payment.ini
    regexp: '^uid'
    replace: "uid = {{APPUSER.uid}}"

