- name: Copy LogStash Configuration
  template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart LogStash
  systemd:
    name: logstash
    state: restarted

- name: Wait for logstash to open the port
  wait_for:
    port: 5044
    delay: 40
    timeout: 60