- name: Copy logstash configuration
  template: logstash.conf
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  systemd:
    name: logstash
    state: restarted
