- name: Copy Prometheus Configuration
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart LogStash
  systemd:
    name: prometheus
    state: restarted

- name: Wait for Prometheus to open the port
  wait_for:
    port: 9090
    delay: 10
    timeout: 30