- name: Setup HostName
  shell: set-hostname {{COMPONENT}}

- name: Install AWS Boto Python Modules
  pip:
    name: "{{item}}"
    executable: pip3
  loop:
    - botocore
    - boto3
    -
- name: Download DocumentDB PEM File
  when: MONGO_CONNECT is defined
  become_user: roboshop
  get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: "/home/roboshop/rds-combined-ca-bundle.pem"

- name: lookup secretsmanager secret in the current region
  shell: "echo {{ lookup('amazon.aws.aws_secret', 'dev/roboshop/secrets', region='us-east-1') | to_json }} | jq"
  register: out

- name: fetching the secret
  set_fact:
    secrets: "{{ out.stdout | from_json }}"

