- name: Setup HostName
  shell: set-hostname {{COMPONENT}}

- name: Install AWS Boto Python Modules
  pip:
    name: "{{item}}"
    executable: pip3
  loop:
    - botocore
    - boto3

- name: Download DocumentDB PEM File
  when: MONGO_CONNECT is defined
  become_user: roboshop
  get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: "/home/roboshop/rds-combined-ca-bundle.pem"

- name: Fetch Secrets from Secret manager
  shell: "echo {{lookup('amazon.aws.aws_secret', '{{ENV}}/roboshop/secrets', region='us-east-1') | to_json}} | jq > /tmp/secret.txt"
  register: out

- name: save the secret
  set_fact:
    secrets: "{{ out.stdout | from_json }}"

