- name: Installing Maven
  ansible.builtin.package:
    name: maven
    state: present

- name: Download and extract {{COMPONENT}} and create App User
  include_role:
    name: common
    tasks_from: download

# Commenting this as package will be downloaded from the CI'ed Nexus
#- name: Make maven package
#  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
#  args:
#    chdir: /home/roboshop/{{COMPONENT}}
#  become_user: roboshop

- name: Copy SystemD and Start Service
  include_role:
    name: common
    tasks_from: systemd

- name: Configure Rsyslog
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Configure Filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Installing Node_Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node-exporter