- name: Adding Application User
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Application User
  register: APPUSER

- name: Clearing Old Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path:  /home/roboshop/{{COMPONENT}}
    state: directory
    mode: '0775'
  become_user: roboshop

- name: Download and Extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: http://172.31.5.224:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  become_user: root