- name: Copy {{COMPONENT}} systemd
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}}
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: restarted
    daemon_reload: yes
    enabled: yes